This revives the hokey old testing framework.  Run "./do-test" from the test directory.
Also, some test updates:

    Disable the broken test 000.

    Add a new test 100: run random-hab and two bionet-watchers, and make
    sure all the output is exactly the same.  Currently passes.  :-)

diff --git a/test/do-test b/test/do-test
--- a/test/do-test
+++ b/test/do-test
@@ -1,62 +1,43 @@
-#!/bin/sh
+#!/bin/bash
 
+export ROOT="$(pwd)/.."
 
-if [ -z "$TEST_USER" ]; then
-    export TEST_USER='root'
-    #export TEST_USER=''
-    echo "TEST_USER unset, using default $TEST_USER"
-fi
+NUM_SKIPPED=0
+NUM_PASSED=0
+NUM_FAILED=0
 
-if [ -z "$TEST_MACHINE" ]; then
-    export TEST_MACHINE=bionet-remote-basestation.local
-    #export TEST_MACHINE=slurp
-    echo "TEST_MACHINE unset, using default $TEST_MACHINE"
-fi
-
-if [ -z "$TEST_USER" ]; then
-    export TEST_DEST="${TEST_MACHINE}"
-else 
-    export TEST_DEST="${TEST_USER}@${TEST_MACHINE}"
-fi
-
-
-export TEST_DIR="/tmp/bionet-test-$(hostname)-$$"
-
-export CAL_PD_MODULES="bdp dnssd"
-
-
-function cleanup_test_environment () {
-    echo "cleaning up test environment for '${TEST_DEST}'"
-    ssh ${TEST_DEST} rm -rf ${TEST_DIR}
-}
-
-trap 'echo caught signal; exit 1' INT TERM
-trap 'echo bye; cleanup_test_environment' EXIT
-
-
-echo "setting up test environment for '${TEST_DEST}'"
-ssh ${TEST_DEST} mkdir ${TEST_DIR}
-
-
-# now run all the tests
 for TEST in $(ls -1d tests/* | sort); do
     [ ! -d "$TEST" ] && continue
 
-    echo 
-    echo "*** ${TEST}"
     echo
+    echo "*** ${TEST}"
 
-    pushd "$TEST"
+    if [ ! -x "$TEST/run" ]; then
+        echo "disabled, skipping"
+        NUM_SKIPPED=$(($NUM_SKIPPED+1))
+        continue
+    fi
+
+    pushd "$TEST" > /dev/null
     ./run
     if [ $? -eq 0 ]; then
-        echo "    TEST PASSED!"
-    elif [ $? -eq 1 ]; then
-        echo "    TEST FAILED!"
-    else 
-        echo "    TEST did not complete"
+        echo "TEST PASSED!"
+        NUM_PASSED=$(($NUM_PASSED+1))
+    else
+        echo "TEST FAILED!"
+        NUM_FAILED=$(($NUM_FAILED+1))
     fi
-    popd
-    
-    echo
+    popd > /dev/null
 done
+
+echo
+echo "passed: $NUM_PASSED"
+echo "failed: $NUM_FAILED"
+echo "skipped: $NUM_SKIPPED"
+
+if [ "$NUM_FAILED" = 0 ]; then
+    exit 0
+else
+    exit 1
+fi
 
