Try to get buildbot to report warnings on valgrind errors

diff --git a/test/do-test b/test/do-test
--- a/test/do-test
+++ b/test/do-test
@@ -11,6 +11,8 @@ export ROOT="$(pwd)/.."
 NUM_SKIPPED=0
 NUM_PASSED=0
 NUM_FAILED=0
+NUM_WARN=0
+NUM_TOTAL=0
 FAIL_REPORT=""
 
 TESTS=$@
@@ -35,42 +37,54 @@ for TEST in $TESTS; do
         continue
     fi
 
+    NUM_TOTAL=$(($NUM_TOTAL+1))
+
     pushd "$TEST" > /dev/null
     ./run
     RC=$?
-    if [ $RC -eq 0 ]; then
+    if [ $RC -eq $TEST_SUCCEED_CODE ]; then
         echo "TEST PASSED!"
         NUM_PASSED=$(($NUM_PASSED+1))
     else
-        if [ $RC -eq 3 ]; then
+        if [ $RC -eq $TEST_SKIP_CODE ]; then
             echo "test disabled itself, skipping"
             NUM_SKIPPED=$(($NUM_SKIPPED+1))
+	    FAIL_REPORT="${TEST}:skip:Command returned skip code"
+        elif [ $RC -eq $TEST_WARNING_CODE ]; then
+            echo "TEST WARNING!"
+            NUM_WARN=$(($NUM_WARN+1))
+	    FAIL_REPORT="${TEST}:warning:Command returned warning code"
         else
             echo "TEST FAILED!"
             NUM_FAILED=$(($NUM_FAILED+1))
-	    FAIL_REPORT="${FAIL_REPORT} ${TEST}"
+	    FAIL_REPORT="${TEST}:failure:Command returned fail code"
         fi
     fi
     popd > /dev/null
 done
 
 
-if [ "$NUM_FAILED" != 0 ]; then
-	echo
-	echo "Failed Tests:"
-	for fail in $FAIL_REPORT; do
-		echo "  $fail"
-	done
-fi
+echo
+echo "Test Report:"
+for line in $FAIL_REPORT; do
+	echo "$line"
+done
+
+rate=`expr \( $NUM_PASSED \* 100 \) /  $NUM_TOTAL`
 
 echo
 echo "passed: $NUM_PASSED"
 echo "failed: $NUM_FAILED"
+echo "warnings: $NUM_WARN"
 echo "skipped: $NUM_SKIPPED"
+echo "$rate%: Tests: $NUM_TOTAL, Failures: $NUM_FAILED, Warnings: $NUM_WARN"
 
-if [ "$NUM_FAILED" = 0 ]; then
+if [ "$NUM_FAILED" -gt 0 ]; then
+    exit 1
+elif [ "$NUM_WARN" -gt 0 ]; then
+    #Buildbot should parse out warnings
     exit 0
 else
-    exit 1
+    exit 0
 fi
 
