Add sync ack sync-config setting

diff --git a/test/tests/121.bdmsync-over-ion-with-kill/run b/test/tests/121.bdmsync-over-ion-with-kill/run
--- a/test/tests/121.bdmsync-over-ion-with-kill/run
+++ b/test/tests/121.bdmsync-over-ion-with-kill/run
@@ -160,6 +160,11 @@ else
     echo "Sync'd BDM output is identical to original, yay"
 fi
 
+if ! check_db_sync_acks orig-bdm.db; then
+    echo "ERROR: Some syncs still unacknowledged"
+    RETVAL=1
+fi
+
 # see what we got
 bpstats
 
