Fix blocked-write test to actually detect write-blocking errors Fix missing datapoints when a peer is disconnected due to a blocked write

diff --git a/test/tests/402.write-blocked/run b/test/tests/402.write-blocked/run
--- a/test/tests/402.write-blocked/run
+++ b/test/tests/402.write-blocked/run
@@ -38,8 +38,11 @@ else
     export PYTHONPATH=$PYPATHADD:$PYTHONPATH
 fi
 
-echo Making the test pattern output
-sed -e "s/XXPIDXX/$UNIQUE/" < testpattern.out.save > testpattern.out
+echo Making the test pattern input/output
+sed -e "s/XXPIDXX/$UNIQUE/" < testpattern.out.head > testpattern.out
+cat testpattern.in > testpattern.in.big
+perl make_test_pattern.pl $UNIQUE >> testpattern.in.big 2>>testpattern.out
+sed -e "s/XXPIDXX/$UNIQUE/" < testpattern.out.tail >> testpattern.out
 
 echo starting first bionet-watcher
 $ROOT/client/watcher/bionet-watcher --habs "test-pattern-hab.$UNIQUE" --nodes "test-pattern-hab.$UNIQUE.*" --resources "test-pattern-hab.$UNIQUE.*:*" >| out.watcher.0 &
@@ -49,8 +52,9 @@ echo starting second bionet-watcher
 $ROOT/client/watcher/bionet-watcher --habs "test-pattern-hab.$UNIQUE" --nodes "test-pattern-hab.$UNIQUE.*" --resources "test-pattern-hab.$UNIQUE.*:*" >| out.watcher.1 &
 WATCH2PID=$!
 
+
 echo Starting test-pattern-hab
-$ROOT/hab/test-pattern/test-pattern-hab -i $UNIQUE testpattern.in > /dev/null &
+$ROOT/hab/test-pattern/test-pattern-hab -i $UNIQUE testpattern.in.big &
 TPHPID=$!
 echo "[$!]"
 
@@ -58,29 +62,54 @@ sleep 5 # Let the watcher connect
 echo Sending SIGSTOP to second watcher
 kill -STOP $WATCH2PID
 
-echo "Waiting for test-pattern-hab"
+MYTIMEOUT=100
+echo "Waiting $MYTIMEOUT seconds for test-pattern-hab"
 x=0
 while test "$x" -lt 500; do
-    kill -0 $TPHPID || break
+    kill -0 $TPHPID 2>/dev/null || break
     sleep 1
     x=`expr $x + 1`
+    echo -n "."
 done
-kill -9 $WATCH2PID
+echo
+
+if kill -0 $TPHPID 2> /dev/null; then
+    echo "ERROR: test-pattern-hab still running after $MYTIMEOUT seconds"
+    echo "This indicated it is blocking on a write"
+    RETVAL=1
+    kill -9 $TPHPID
+else
+	echo "test-pattern-hab finished"
+fi
+
+# The hab has gone away. Allow this client to continue to ensure that 
+# any bugs weren't masked by the TCP send/recv buffers
+kill -CONT $WATCH2PID
 
 
 
 sleep 4  # to let the clients notice
 
-echo "killing bionet-watcher 1"
+echo "killing bionet-watcher 1 and 2"
 kill $WATCH1PID
 wait $WATCH1PID
+kill $WATCH2PID
+wait $WATCH2PID
 
 if ! diff -q out.watcher.0 testpattern.out; then
-    echo "ERROR: watcher output differs from test-pattern-hab output:"
-    diff -u testpattern.out out.watcher.0
+    echo "ERROR: watcher output differs from test-pattern-hab output"
+    echo "Differences not shown. Look at output of:"
+    echo "  diff -u testpattern.out out.watcher.0"
     RETVAL=1
 else
     echo "watcher outputs are identical to test-pattern-hab output, yay"
+fi
+
+
+if  diff -q out.watcher.1 testpattern.out; then
+    echo "ERROR: bad watcher output is the same as test-pattern-hab output"
+    echo " This means the TCP send/recv buffers masked any errors that may have occured"
+    RETVAL=1
 fi
 
 exit $RETVAL
