Update tests for new output format(s)
Tests normalize output by removing event timestamp before comparing hab and BDM watcher/client outputs

diff --git a/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run b/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run
--- a/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run
+++ b/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run
@@ -16,6 +16,8 @@ if [ -z "$TEST_DURATION" ]; then
     TEST_DURATION=30
 fi
 
+. ../../testlib.sh
+
 UNIQUE=$$
 SYNCUNIQUE=${HOSTNAME//\./-}
 RETVAL=0
@@ -68,7 +70,8 @@ kill $HABPID
 wait $HABPID
 
 sleep 15
-$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig
+#$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig
+$ROOT/data-manager/client/bdm-client/bdm-client -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig 2> err.bdm-sync
 echo "test run complete. killing the TCP sync sender BDM"
 kill $SENDPID
 wait $SENDPID
@@ -76,7 +79,8 @@ wait $SENDPID
 echo "getting data from TCP sync receiver BDM"
 
 
-$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync
+#$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync
+$ROOT/data-manager/client/bdm-client/bdm-client -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync 2>err.bdm-sync
 
 echo "killing BDM"
 kill $RECVPID
@@ -86,20 +90,25 @@ fi
 wait
 
 
-if ! diff -q out.random-hab out.bdm-orig; then
-    echo "ERROR: Originating BDM output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-orig
-    RETVAL=1
-else
-    echo "Originating BDM output is identical to random-hab output, yay"
-fi
+normalize_bdm_client out.random-hab > norm.random-hab
 
-if ! diff -q out.random-hab out.bdm-sync; then
-    echo "ERROR: Sync'd BDM output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-sync
+for x in bdm-orig bdm-sync; do
+    normalize_bdm_client out.$x > norm.$x
+    if ! diff -q norm.random-hab norm.$x; then
+	echo "ERROR: $x output differs from random-hab output:"
+	diff -u norm.random-hab norm.$x
+	RETVAL=1
+    else
+	echo "$x output is identical to random-hab output, yay"
+    fi
+done
+
+if ! diff -q out.bdm-orig out.bdm-sync; then
+    echo "ERROR: Sync'd BDM output differs from Original:"
+    diff -u out.bdm-orig out.bdm-sync
     RETVAL=1
 else
-    echo "Sync'd BDM output is identical to random-hab output, yay"
+    echo "Sync'd BDM output is identical to original, yay"
 fi
 
 
diff --git a/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run b/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run
--- a/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run
+++ b/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run
@@ -15,6 +15,7 @@ if [ -z "$TEST_DURATION" ]; then
     TEST_DURATION=30
 fi
 
+. $ROOT/test/testlib.sh
 
 UNIQUE=$$
 SYNCUNIQUE=${HOSTNAME//\./-}
@@ -24,6 +25,8 @@ RETVAL=0
 YEAR=`date +%Y`
 PREV_YEAR=$(($YEAR-1))
 NEXT_YEAR=$(($YEAR+1))
+
+rm -f core core.*
 
 echo "making DB file"
 rm -f bdm.db
@@ -78,20 +81,25 @@ echo "killing BDM"
 kill $RCVPID
 wait $RCVPID
 
-if ! diff -q out.random-hab out.bdm-orig; then
-    echo "ERROR: Originating BDM output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-orig
-    RETVAL=1
-else
-    echo "Originating BDM output is identical to random-hab output, yay"
-fi
+normalize_bdm_client out.random-hab > norm.random-hab
 
-if ! diff -q out.random-hab out.bdm-sync; then
-    echo "ERROR: Sync'd BDM output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-sync
+for x in bdm-orig bdm-sync; do
+    normalize_bdm_client out.$x > norm.$x
+    if ! diff -q norm.random-hab norm.$x; then
+	echo "ERROR: $x output differs from random-hab output:"
+	diff -u norm.random-hab norm.$x
+	RETVAL=1
+    else
+	echo "$x output is identical to random-hab output, yay"
+    fi
+done
+
+if ! diff -q out.bdm-orig out.bdm-sync; then
+    echo "ERROR: Sync'd BDM output differs from Original:"
+    diff -u out.bdm-orig out.bdm-sync
     RETVAL=1
 else
-    echo "Sync'd BDM output is identical to random-hab output, yay"
+    echo "Sync'd BDM output is identical to original, yay"
 fi
 
 exit $RETVAL
diff --git a/test/tests/120.bdmsync-over-ion/run b/test/tests/120.bdmsync-over-ion/run
--- a/test/tests/120.bdmsync-over-ion/run
+++ b/test/tests/120.bdmsync-over-ion/run
@@ -6,6 +6,7 @@
 #
 
 
+
 if [ -z "$ROOT" ]; then
     echo "ROOT environment variable is undefined"
     exit 1
@@ -15,7 +16,7 @@ if [ -z "$TEST_DURATION" ]; then
     TEST_DURATION=30
 fi
 
-
+. $ROOT/test/testlib.sh
 . $ROOT/test/config.sh
 
 if [ -z "$ENABLE_ION" ]; then
@@ -43,13 +44,13 @@ YEAR=`date +%Y`
 PREV_YEAR=$(($YEAR-1))
 NEXT_YEAR=$(($YEAR+1))
 
+ulimit -Sc unlimited
+rm -f core core.*
 
 rm -f ion.log
 
-echo "making DB file"
-rm -f orig-bdm.db
-sqlite3 orig-bdm.db < $ROOT/data-manager/server/schema
-cp orig-bdm.db sync-bdm.db
+echo "removing old DB file, and allowing bionet-data-manger to create schema"
+rm -f orig-bdm.db sync-bdm.db
 
 echo starting ION Loopback interface
 CONFIGDIR="./ionconfig"
@@ -62,43 +63,64 @@ ionstart                           \
 
 # receive the message and store it in a file via test bundle sink
 echo "Starting ION sync receiver BDM"
-$ROOT/data-manager/server/bionet-data-manager --file sync-bdm.db --id sync-recv-$SYNCUNIQUE --no-resources --dtn-endpoint-id 'ipn:1.1' --dtn-sync-receiver &
+rm -f sync-recv.log
+$ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file sync-bdm.db --id sync-recv-$SYNCUNIQUE --no-resources --dtn-endpoint-id 'ipn:1.1' --dtn-sync-receiver  --debug --log-file=sync-recv.log &
+RECVPID=$!
 
 echo starting ION sync sender BDM
-$ROOT/data-manager/server/bionet-data-manager --file orig-bdm.db --id sync-send-$SYNCUNIQUE --filter "random-hab.$UNIQUE.*:*" --dtn-endpoint-id 'ipn:1.2' --sync-sender-config  bdm-sync-send.cfg --port 11111 &
+rm -f sync-send.log
+$ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file orig-bdm.db --id sync-send-$SYNCUNIQUE --filter "random-hab.$UNIQUE.*:*" --dtn-endpoint-id 'ipn:1.2' --sync-sender-config  bdm-sync-send.cfg --port 11111  --debug --log-file=sync-send.log &
+SENDPID=$!
 sleep 12 # let the bdm come up before starting the HAB
 
 echo starting random-hab
 $ROOT/hab/random/random-hab --id $UNIQUE --output-mode bdm-client --max-delay 1 >| out.random-hab &
+HABPID=$!
 
 echo "Generating data for a while..."
 sleep $TEST_DURATION
 
 
-echo "test run complete, killing random-hab"
-kill %3
-wait %3
+echo "killing random-hab"
+kill $HABPID
+wait $HABPID
 
 echo "Waiting for all data to sync"
 sleep 30
+$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig
 echo "killing the ION sync sender BDM"
-kill %2
-wait %2
+kill $SENDPID
+wait $SENDPID
 
 echo "getting data from TCP sync receiver BDM"
 
-$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-client.py
+
+$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync
 
 echo "killing ION Sync Receive BDM"
-kill %1
-wait
+kill $RECVPID
+wait $RECVPID
 
-if ! diff -q out.random-hab out.bdm-client.py; then
-    echo "ERROR: bdm-client.py output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-client.py
+
+normalize_bdm_client out.random-hab > norm.random-hab
+
+for x in bdm-orig bdm-sync; do
+    normalize_bdm_client out.$x > norm.$x
+    if ! diff -q norm.random-hab norm.$x; then
+	echo "ERROR: $x output differs from random-hab output:"
+	diff -u norm.random-hab norm.$x
+	RETVAL=1
+    else
+	echo "$x output is identical to random-hab output, yay"
+    fi
+done
+
+if ! diff -q out.bdm-orig out.bdm-sync; then
+    echo "ERROR: Sync'd BDM output differs from Original:"
+    diff -u out.bdm-orig out.bdm-sync
     RETVAL=1
 else
-    echo "bdm-client.py output is identical to random-hab output, yay"
+    echo "Sync'd BDM output is identical to original, yay"
 fi
 
 # see what we got
diff --git a/test/tests/130.random-hab-and-bdm-watcher/run b/test/tests/130.random-hab-and-bdm-watcher/run
--- a/test/tests/130.random-hab-and-bdm-watcher/run
+++ b/test/tests/130.random-hab-and-bdm-watcher/run
@@ -5,6 +5,8 @@
 # NNC07CB47C.
 #
 
+#Define to run with a test-pattern file, instead of random
+#TEST_PATTERN=testpattern.in.a
 
 if [ -z "$ROOT" ]; then
     echo "ROOT environment variable is undefined"
@@ -26,6 +28,7 @@ PREV_YEAR=$(($YEAR-1))
 NEXT_YEAR=$(($YEAR+1))
 
 ulimit -Sc unlimited
+rm -f core core.*
 
 make_bdm_db "bdm.db"
 
@@ -35,7 +38,7 @@ $ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --id "bdm-$UNIQUE"
 BDMPID=$!
 sleep 3 # let the bdm come up before starting the HAB
 
-WATCHCMD="$ROOT/data-manager/client/bdm-watcher/bdm-watcher --output-mode 'bdm-client' -T '$PREV_YEAR-01-01 00:00:00' -t '$NEXT_YEAR-12-31 12:59:59' -r 'bdm-$UNIQUE,bdm-$UNIQUE/random-hab.$UNIQUE.*:*'"
+WATCHCMD="$ROOT/data-manager/client/bdm-watcher/bdm-watcher --output-mode 'bdm-client' -T '$PREV_YEAR-01-01 00:00:00' -t '$NEXT_YEAR-12-31 12:59:59' --habs 'bdm-$UNIQUE,bdm-$UNIQUE/random-hab.$UNIQUE' --nodes 'bdm-$UNIQUE,bdm-$UNIQUE/random-hab.$UNIQUE.*' --resources 'bdm-$UNIQUE,bdm-$UNIQUE/random-hab.$UNIQUE.*:*'"
 
 echo "bdm-watcher args: $WATCHCMD"
 
@@ -45,14 +48,19 @@ eval "$WATCHCMD >| out.bdm-watcher.0 &"
 WPID0=$!
 
 
-test_log "Starting test-pattern-hab recorder"
-rm -f testpattern.in
-$ROOT/client/watcher/bionet-watcher --output-mode 'test-pattern' > testpattern.in &
-TPPID=$!
+if [ "$TEST_PATTERN" != "testpattern.in" ]; then
+  test_log "Starting test-pattern-hab recorder"
+  rm -f testpattern.in
+  $ROOT/client/watcher/bionet-watcher --output-mode 'test-pattern' > testpattern.in &
+  TPPID=$!
+fi
 
 test_log "starting random-hab"
-$ROOT/hab/random/random-hab --id $UNIQUE --output-mode bdm-client --max-delay 1 >| out.random-hab &
-#$ROOT/hab/test-pattern/test-pattern-hab --id $UNIQUE --type random-hab --output-mode bdm-client --current-time testpattern.in >| out.random-hab &
+if [ -z "$TEST_PATTERN" ]; then
+  $ROOT/hab/random/random-hab --id $UNIQUE --output-mode bdm-client --max-delay 1 >| out.random-hab &
+else
+  $ROOT/hab/test-pattern/test-pattern-hab --id $UNIQUE --type random-hab --output-mode bionet-watcher --current-time "$TEST_PATTERN" >| out.random-hab &
+fi
 HABPID=$!
 
 sleep `expr $TEST_DURATION / 2`
@@ -61,11 +69,17 @@ test_log "some datapoints generated, starting bdm-watcher.1"
 eval "$WATCHCMD >| out.bdm-watcher.1 &"
 WPID1=$!
 
-sleep `expr $TEST_DURATION / 2`
+if [ -z "$TEST_PATTERN" ]; then
+  sleep `expr $TEST_DURATION / 2`
 
-test_log "all datapoints generated. Killing random-hab"
-kill $HABPID
-wait $HABPID
+  test_log "all datapoints generated. Killing random-hab"
+  kill $HABPID
+  wait $HABPID
+else
+  wait $HABPID
+  test_log "all datapoints generated. test-pattern-hab exited"
+fi
+
 
 # Let the BDM commit the last info to disk
 sleep 10
@@ -91,17 +105,34 @@ test_log "killing BDM"
 kill $BDMPID
 wait $BDMPID
 
-kill $TPPID
-wait $TPPID
+if [ -n "$TPPID" ]; then
+  kill $TPPID
+  wait $TPPID
+fi
 
+
+normalize_bdm_client out.random-hab > norm.random-hab
 for i in 0 1 2; do
+    normalize_bdm_client out.bdm-watcher.$i > norm.bdm-watcher.$i
     sort out.bdm-watcher.$i > sorted.bdm-watcher.$i
-    if ! diff -q out.random-hab sorted.bdm-watcher.$i; then
+
+    if ! diff -q norm.random-hab norm.bdm-watcher.$i; then
 	echo "ERROR: bdm-watcher.$i output differs from random-hab output:"
-	diff -u out.random-hab sorted.bdm-watcher.$i
+	#diff -u norm.random-hab norm.bdm-watcher.$i
 	RETVAL=1
     else
-	echo "bdm-watcher.$i same as random-hab output:"
+	echo "bdm-watcher.$i same as random-hab output"
+    fi
+
+done
+
+for i in 1 2; do
+    if ! diff -q sorted.bdm-watcher.0 sorted.bdm-watcher.$i; then
+	echo "ERROR: bdm-watcher.$i output differs from bdm-watcher.0 output:"
+	#diff -u norm.random-hab norm.bdm-watcher.$i
+	RETVAL=1
+    else
+	echo "bdm-watcher.$i same as bdm-watcher.0 output"
     fi
 done
 
diff --git a/test/tests/131.bdmsync-over-tcp-random-to-bdm-to-bdm-to-watcher/run b/test/tests/131.bdmsync-over-tcp-random-to-bdm-to-bdm-to-watcher/run
--- a/test/tests/131.bdmsync-over-tcp-random-to-bdm-to-bdm-to-watcher/run
+++ b/test/tests/131.bdmsync-over-tcp-random-to-bdm-to-bdm-to-watcher/run
@@ -27,6 +27,7 @@ PREV_YEAR=$(($YEAR-1))
 NEXT_YEAR=$(($YEAR+1))
 
 #Generate core files on error
+rm -f core core.*
 ulimit -Sc unlimited
 
 echo "making DB file"
@@ -53,7 +54,7 @@ echo " ->  $ROOT/data-manager/server/bionet-data-manager $SENDPID"
 sleep 6 # let the bdm come up before starting the HAB
 
 
-WATCHCMD="$ROOT/data-manager/client/bdm-watcher/bdm-watcher --output-mode 'bdm-client' -T '$PREV_YEAR-01-01 00:00:00' -t '$NEXT_YEAR-12-31 12:59:59' -r 'sync-recv-$SYNCUNIQUE,sync-send-$SYNCUNIQUE/random-hab.$UNIQUE.*:*'"
+WATCHCMD="$ROOT/data-manager/client/bdm-watcher/bdm-watcher --output-mode 'bdm-client' -T '$PREV_YEAR-01-01 00:00:00' -t '$NEXT_YEAR-12-31 12:59:59' -h 'sync-recv-$SYNCUNIQUE,sync-send-$SYNCUNIQUE/random-hab.$UNIQUE' -n 'sync-recv-$SYNCUNIQUE,sync-send-$SYNCUNIQUE/random-hab.$UNIQUE.*'  -r 'sync-recv-$SYNCUNIQUE,sync-send-$SYNCUNIQUE/random-hab.$UNIQUE.*:*'"
 
 echo "bdm-watcher args: $WATCHCMD"
 
@@ -110,14 +111,25 @@ wait $RECVPID
 kill $TPPID
 wait $TPPID
 
-for i in out.bdm-watcher.0 out.bdm-watcher.1 out.bdm-watcher.2 out.bdm-orig; do
-    sort $i > $i.sorted
-    if ! diff -q out.random-hab $i.sorted; then
-	echo "ERROR: $i output differs from random-hab output:"
-	diff -u out.random-hab $i.sorted
+normalize_bdm_client out.random-hab > norm.random-hab
+normalize_bdm_client out.bdm-orig > norm.bdm-orig
+sort out.bdm-orig > sorted.bdm-orig
+if ! diff -q norm.random-hab norm.bdm-orig; then
+    echo "ERROR: bdm-orig output differs from random-hab output:"
+    diff -u norm.random-hab norm.bdm-orig
+    RETVAL=1
+else
+    echo "bdm-orig output same as random-hab output"
+fi
+
+for i in bdm-watcher.0 bdm-watcher.1 bdm-watcher.2; do
+    sort out.$i > sorted.$i
+    if ! diff -q sorted.bdm-orig sorted.$i; then
+	echo "ERROR: $i output differs from bdm-orig output:"
+	diff -u sorted.bdm-orig sorted.$i
 	RETVAL=1
     else
-	echo "$i output same as random-hab output"
+	echo "$i output same as bdm-orig output"
     fi
 done
 
diff --git a/test/tests/132.adding-bdm-subscriptions/run b/test/tests/132.adding-bdm-subscriptions/run
--- a/test/tests/132.adding-bdm-subscriptions/run
+++ b/test/tests/132.adding-bdm-subscriptions/run
@@ -112,11 +112,27 @@ echo "killing BDM"
 kill $BDMPID
 wait
 
-for log in out.client.0 out.client.1; do
-    cat out.random-hab.A out.random-hab.B | sort > sorted.random-habs
-    sort $log > sorted.$log
-    if ! diff -q sorted.random-habs sorted.$log; then
+# NOTE: The BDM may not see the same order as the combined random-hab logs
+# when both habs do something at essentially the same time, so when comparing the
+# combined hab output, we must sort after trimming the event timestamp
+cat out.random-hab.A out.random-hab.B | grep '+D' > datapoints.random-habs
+normalize_bdm_client datapoints.random-habs | sort  > sorted.norm.random-habs
+
+for log in out.client.0; do
+    normalize_bdm_client $log | sort  > sorted.norm.$log
+    if ! diff -q sorted.norm.random-habs sorted.norm.$log; then
 	echo "ERROR: $log output differs from random-hab output:"
+	diff -u sorted.norm.random-habs sorted.norm.$log
+	RETVAL=1
+    fi
+done
+
+# Verify that both clients saw the same timestamps
+sort out.client.0 > sorted.out.client.0
+for log in out.client.1; do
+    sort $log > sorted.$log
+    if ! diff -q sorted.out.client.0 sorted.$log; then
+	echo "ERROR: $log output differs from client 0	output:"
 	diff -u sorted.random-habs sorted.$log
 	RETVAL=1
     fi
diff --git a/test/tests/204.valgrind-memcheck-bdmsync-tcp/run b/test/tests/204.valgrind-memcheck-bdmsync-tcp/run
--- a/test/tests/204.valgrind-memcheck-bdmsync-tcp/run
+++ b/test/tests/204.valgrind-memcheck-bdmsync-tcp/run
@@ -42,7 +42,7 @@ cp orig-bdm.db sync-bdm.db
 export G_SLICE=always-malloc 
 export G_DEBUG=gc-friendly,resident-modules
 
-DOVALGRIND="$LIBTOOL --mode=execute valgrind --suppressions=valgrind.suppressions$VGSUPPRESSIONS_SUFFIX --quiet --tool=memcheck --trace-children=yes $VGLEAK"
+DOVALGRIND="$LIBTOOL --mode=execute valgrind --suppressions=valgrind.suppressions$VGSUPPRESSIONS_SUFFIX --quiet --tool=memcheck --trace-children=yes --track-origins=yes $VGLEAK"
 
 echo starting TCP sync receiver BDM
 $DOVALGRIND --log-file=log.vg.recv $ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file sync-bdm.db --id sync-receive-$SYNCUNIQUE --no-resources --tcp-sync-receiver &
@@ -78,22 +78,29 @@ echo "killing BDM"
 kill $RECVPID
 wait $RECVPID
 
-if ! diff -q out.random-hab out.bdm-orig; then
-    echo "ERROR: Originating BDM output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-orig
+normalize_bdm_client out.random-hab  > norm.random-hab
+
+for log in bdm-orig; do
+    normalize_bdm_client out.$log > norm.$log
+    if ! diff -q norm.random-hab norm.$log; then
+	echo "ERROR: $log BDM output differs from random-hab output:"
+	diff -u norm.random-hab norm.$log
+	RETVAL=1
+    else
+	echo "$log BDM output is identical to random-hab output, yay"
+    fi
+done
+
+sort out.bdm-orig > sorted.bdm-orig
+sort out.bdm-sync > sorted.bdm-sync
+
+if ! diff -q sorted.bdm-orig sorted.bdm-sync; then
+    echo "ERROR: Origional BDM output differs from sync'd:"
+    diff -u sorted.bdm-orig sorted.bdm-sync
     RETVAL=1
 else
-    echo "Originating BDM output is identical to random-hab output, yay"
+    echo "Origional BDM output identical to sync'd, yay"
 fi
-
-if ! diff -q out.random-hab out.bdm-sync; then
-    echo "ERROR: Sync'd BDM output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-sync
-    RETVAL=1
-else
-    echo "Sync'd BDM output is identical to random-hab output, yay"
-fi
-
 
 for log in log.vg.send log.vg.recv; do
     if [ $(wc -l < $log) -gt 0 ]; then
