add more diffs to the tests so we can tell where the data wasn't captured.
make test 111 kill the BDM in the middle of the test and the restart it and see the sync'ing continue.

diff --git a/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run b/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run
--- a/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run
+++ b/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/run
@@ -15,6 +15,13 @@ if [ -z "$TEST_DURATION" ]; then
     TEST_DURATION=30
 fi
 
+if [ -z "$PYTHONPATH" ]; then
+    export PYTHONPATH=$ROOT/data-manager/py-client:$ROOT/data-manager/py-client/.libs
+else
+    export PYTHONPATH=$ROOT/data-manager/py-client:$ROOT/data-manager/py-client/.libs:$PYTHONPATH
+fi
+export DYLD_LIBRARY_PATH=$ROOT/util/.libs:$ROOT/asn.1/.libs
+export LD_LIBRARY_PATH=$ROOT/util/.libs:$ROOT/asn.1/.libs
 
 UNIQUE=$$
 RETVAL=0
@@ -49,34 +56,36 @@ kill %3
 wait %3
 
 sleep 10
+$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig
 echo "test run complete. killing the TCP sync sender BDM"
 kill %2
 kill %2
 
 echo "getting data from TCP sync receiver BDM"
-if [ -z "$PYTHONPATH" ]; then
-    export PYTHONPATH=$ROOT/data-manager/py-client:$ROOT/data-manager/py-client/.libs
-else
-    export PYTHONPATH=$ROOT/data-manager/py-client:$ROOT/data-manager/py-client/.libs:$PYTHONPATH
-fi
-export DYLD_LIBRARY_PATH=$ROOT/util/.libs:$ROOT/asn.1/.libs
-export LD_LIBRARY_PATH=$ROOT/util/.libs:$ROOT/asn.1/.libs
 
 
-
-$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-client.py
+$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync
 
 echo "killing BDM"
 kill %1
 wait
 
-if ! diff -q out.random-hab out.bdm-client.py; then
-    echo "ERROR: bdm-client.py output differs from random-hab output:"
-    diff -u out.random-hab out.bdm-client.py
+if ! diff -q out.random-hab out.bdm-orig; then
+    echo "ERROR: Originating BDM output differs from random-hab output:"
+    diff -u out.random-hab out.bdm-orig
     RETVAL=1
 else
-    echo "bdm-client.py output is identical to random-hab output, yay"
+    echo "Originating BDM output is identical to random-hab output, yay"
 fi
+
+if ! diff -q out.random-hab out.bdm-sync; then
+    echo "ERROR: Sync'd BDM output differs from random-hab output:"
+    diff -u out.random-hab out.bdm-sync
+    RETVAL=1
+else
+    echo "Sync'd BDM output is identical to random-hab output, yay"
+fi
+
 
 exit $RETVAL
 
diff --git a/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run b/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run
--- a/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run
+++ b/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/run
@@ -36,13 +36,21 @@ echo starting TCP sync receiver BDM
 $ROOT/data-manager/server/bionet-data-manager --file sync-bdm.db --id sync-receive --resources "a.a.a:a" --tcp-sync-receiver &
 
 echo starting TCP sync sender BDM
-$ROOT/data-manager/server/bionet-data-manager --file orig-bdm.db --id sync-send --habs "random-hab.$UNIQUE" --nodes "random-hab.$UNIQUE.*" --resources "random-hab.$UNIQUE.*:*" --sync-sender-config $ROOT/test/tests/111.bdmsync-over-tcp-bdm-to-bdm/test.cfg --port 11111 &
+$ROOT/data-manager/server/bionet-data-manager --file orig-bdm.db --id sync-send --habs "random-hab.$UNIQUE" --nodes "random-hab.$UNIQUE.*" --resources "random-hab.$UNIQUE.*:*" --sync-sender-config $ROOT/test/tests/111.bdmsync-over-tcp-random-to-bdm-to-bdm-with-kill/test.cfg --port 11111 &
 sleep 3 # let the bdm come up before starting the HAB
 
 echo starting random-hab
 $ROOT/hab/random/random-hab --id $UNIQUE --output-mode bdm-client --max-delay 1 >| out.random-hab &
 
-sleep 30
+sleep 20
+
+echo "Killing TCP sync receiver BDM"
+kill %1
+wait %1 
+sleep 10
+echo "Restarting TCP sync receiver BDM"
+$ROOT/data-manager/server/bionet-data-manager --file sync-bdm.db --id sync-receive --resources "a.a.a:a" --tcp-sync-receiver &
+
 
 echo "killing random-hab"
 kill %3
@@ -69,15 +77,23 @@ kill %2
 $ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync
 
 echo "killing BDM"
-kill %1
+kill %4
 wait
 
-if ! diff -q out.bdm-orig out.bdm-sync; then
-    echo "ERROR: sync'd BDM output differs from originating BDM output:"
-    diff -u out.bdm-orig out.bdm-sync
+if ! diff -q out.random-hab out.bdm-orig; then
+    echo "ERROR: Originating BDM output differs from random-hab output:"
+    diff -u out.random-hab out.bdm-orig
     RETVAL=1
 else
-    echo "sync'd BDM output is identical to originating BDM output, yay"
+    echo "Originating BDM output is identical to random-hab output, yay"
+fi
+
+if ! diff -q out.random-hab out.bdm-sync; then
+    echo "ERROR: Sync'd BDM output differs from random-hab output:"
+    diff -u out.random-hab out.bdm-sync
+    RETVAL=1
+else
+    echo "Sync'd BDM output is identical to random-hab output, yay"
 fi
 
 exit $RETVAL
