Add check to several sync tests that sync acks clean up after themselves

diff --git a/test/tests/113.bdmsync-tcp-2hop/run b/test/tests/113.bdmsync-tcp-2hop/run
--- a/test/tests/113.bdmsync-tcp-2hop/run
+++ b/test/tests/113.bdmsync-tcp-2hop/run
@@ -173,6 +173,11 @@ for h in A B; do
     done
 done
 
+if ! check_db_sync_acks orig-bdm.db; then
+    echo "ERROR: Some syncs still unacknowledged"
+    RETVAL=1
+fi
+
 if [ $RETVAL -eq 0 ] ; then
     echo "All outputs checkout. Yeah!"
     ./clean
